controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    mecanum_drive_controller:
      type: mecanum_drive_controller/MecanumDriveController

mecanum_drive_controller:
  ros__parameters:
    front_left_wheel_name: "front_left_joint"
    front_right_wheel_name: "front_right_joint"
    back_left_wheel_name: "back_left_joint"  
    back_right_wheel_name: "back_right_joint"

    wheel_separation_x: 0.24  # Distance between front and rear axles
    wheel_separation_y: 0.175  # Distance between left and right wheels
    wheel_radius: 0.075

    robot_base_frame: "base_link"
    use_stamped_vel: false

    # Velocity and acceleration limits
    linear:
      x:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 0.4
        max_acceleration: 0.8
        min_acceleration: -0.8
      y:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 0.4
        max_acceleration: 0.8
        min_acceleration: -0.8

    angular:
      z:
        has_velocity_limits: true
        has_acceleration_limits: true
        max_velocity: 1.0
        max_acceleration: 1.6
        min_acceleration: -1.6

    # Twist command topic
    cmd_vel_topic: cmd_vel
    odom_topic: odom
    
    # Open loop odometry
    open_loop: false
    
    # Publishing
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]