# Vstone 4WDS Rover X40A parameters for official fwdsrover_xna_bringup package
vstone_odometry:
  ros__parameters:
    # Odometry scaling factors (from pub_odom.cpp)
    odom_kvx: 1.0    # Linear X velocity scaling
    odom_kvy: 1.0    # Linear Y velocity scaling  
    odom_kth: 1.0    # Angular velocity scaling
    
    # Frame IDs (matching official package)
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    
    # Robot physical parameters (from official mecanumrover_description URDF)
    wheel_base: 0.24      # Distance between front and rear axles (m) [0.12 - (-0.12)]
    wheel_track: 0.175    # Distance between left and right wheels (m) [0.0875 * 2]
    wheel_radius: 0.075   # Wheel radius (m) - estimated from wheel height