# Vstone 4WDS Rover X40A parameters for official fwdsrover_xna_bringup package
vstone_odometry:
  ros__parameters:
    # Odometry scaling factors (from pub_odom.cpp)
    odom_kvx: 1.0    # Linear X velocity scaling
    odom_kvy: 1.0    # Linear Y velocity scaling  
    odom_kth: 1.0    # Angular velocity scaling
    
    # Frame IDs (matching official package)
    odom_frame_id: "odom"
    base_frame_id: "base_footprint"
    
    # 4WDS Vstone x40a Robot physical parameters
    wheel_base: 0.25     # Distance between front and rear axles (m)
    wheel_track: 0.25    # Distance between left and right wheels (m)
    wheel_radius: 0.07   # Wheel radius (m)
    